export const iconNames = {
  AccountCircle: 'account circle',
  Add: 'add',
  Apps: 'apps',
  ArrowCircleDown: 'arrow circle / down',
  ArrowCircleUp: 'arrow circle / up',
  ArrowDown: 'arrow / drop down',
  ArrowLeft: 'arrow / left',
  ArrowNavigationBackward: 'arrow navigation / backward',
  ArrowNavigationDownward: 'arrow navigation / downward',
  ArrowNavigationForward: 'arrow navigation / forward',
  ArrowNavigationUpward: 'arrow navigation / upward',
  ArrowRight: 'arrow / right',
  ArrowUp: 'arrow / drop up',
  BarChart: 'bar chart',
  Calendar: 'date range',
  Check: 'checkbox / check',
  CheckBoxBlank: 'checkbox / blank',
  CheckBoxIndeterminate: 'checkbox / indeterminate',
  CheckBoxSelected: 'checkbox / selected',
  ChevronDown: 'chevron / down',
  ChevronLeft: 'chevron / left',
  ChevronRight: 'chevron / right',
  ChevronUp: 'chevron / up',
  Close: 'close',
  ColumnCollapse: 'column / collapse',
  ColumnExpand: 'column / expand',
  AddComment: 'comments / comment add',
  Comment: 'comments / comment',
  CommentOutline: 'comments / comment outline',
  Copy: 'copy',
  DataGridCustomizationCols: 'data grid customization / cols',
  DataGridCustomizationRows: 'data grid customization / rows',
  Del: 'delete',
  DensityS: 'data grid density / s',
  DensityM: 'data grid density / m',
  WrapOn: 'data grid settings / wrap on',
  WrapOff: 'data grid settings / wrap off',
  Done: 'done',
  Download: 'download',
  DragIndicator: 'drag indicator',
  EditOn: 'edit on',
  EditOff: 'edit off',
  Error: 'error',
  Exit: 'exit to app',
  Export: 'export',
  Filter: 'filter / on',
  CancelFilter: 'filter / off',
  Group: 'group',
  Help: 'help',
  HistoryRedo: 'history / redo',
  HistoryUndo: 'history / undo',
  Info: 'info',
  Import: 'import',
  Link: 'link',
  List: 'list',
  Unlock: 'lock / unlock',
  Lock: 'lock / lock',
  LockIndeterminate: ' lock / indeterminate',
  LogoNilsen: 'logo icon / nilsen',
  LogoTS5: 'logo icon / ts5',
  LogoTSK: 'logo icon / tsk',
  MagicWand: ' magic wand',
  Marker: 'marker',
  Menu: 'menu',
  MoreHorizontal: 'more / horiz',
  MoreVertical: 'more / vert',
  NewBadge: 'new badge',
  Notification: 'notifications',
  PlayArrow: 'play arrow',
  Refresh: 'refresh',
  Remove: 'remove',
  Restore: 'restore',
  ReplyAll: 'reply all',
  Search: 'search',
  Settings: 'settings',
  ShoppingCart: 'shopping cart',
  SortAZ: 'sort / a-z',
  SortOff: 'sort / off',
  SortZA: 'sort / z-a',
  Star: 'star',
  SubdirectoryArrowRight: 'subdirectory arrow right',
  Sync: 'sync',
  Time: 'time',
  Visibility: 'visibility / on',
  VisibilityOff: 'visibility / off',
  Warning: 'warning / solid',
  WarningOutline: 'warning / outline',
};
